DROP TABLE IF EXISTS "app_user" CASCADE;
DROP TABLE IF EXISTS "country" CASCADE;
DROP TABLE IF EXISTS "avatar" CASCADE;
DROP TABLE IF EXISTS "friendship" CASCADE;
DROP TABLE IF EXISTS "message" CASCADE;

DROP TYPE IF EXISTS  friendship_status CASCADE ;
